## Library

In [1]:
import tensorflow as tf
import numpy as np
from numpy import random
import matplotlib.pyplot as plt
from IPython import display
import pandas as pd 

In [2]:
from numpy import array
from numpy import argmax
from keras.utils import to_categorical

Using TensorFlow backend.


In [3]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

## Data

In [4]:
data = np.loadtxt( 'heart.dat' )
data

array([[70.,  1.,  4., ...,  3.,  3.,  2.],
       [67.,  0.,  3., ...,  0.,  7.,  1.],
       [57.,  1.,  2., ...,  0.,  7.,  2.],
       ...,
       [56.,  0.,  2., ...,  0.,  3.,  1.],
       [57.,  1.,  4., ...,  0.,  6.,  1.],
       [67.,  1.,  4., ...,  3.,  3.,  2.]])

### Target

In [5]:
target = data[:,13]
target

array([2., 1., 2., 1., 1., 1., 2., 2., 2., 2., 1., 1., 1., 2., 1., 1., 2.,
       2., 1., 1., 2., 1., 1., 1., 1., 1., 1., 1., 2., 1., 2., 1., 1., 2.,
       2., 2., 2., 2., 1., 1., 2., 1., 1., 1., 2., 1., 2., 2., 2., 2., 2.,
       1., 1., 1., 1., 1., 2., 1., 2., 2., 1., 2., 1., 1., 1., 2., 1., 2.,
       1., 2., 2., 1., 1., 1., 1., 2., 1., 1., 1., 1., 2., 2., 2., 1., 1.,
       1., 1., 1., 1., 2., 1., 2., 2., 2., 2., 2., 1., 2., 1., 1., 1., 2.,
       1., 2., 2., 2., 1., 2., 2., 1., 2., 1., 2., 1., 1., 1., 2., 2., 1.,
       2., 2., 2., 2., 1., 1., 1., 2., 1., 1., 2., 2., 2., 1., 2., 1., 1.,
       1., 2., 1., 1., 2., 1., 2., 1., 2., 2., 2., 2., 2., 1., 1., 1., 1.,
       1., 1., 1., 2., 1., 1., 2., 2., 2., 1., 2., 1., 1., 1., 1., 1., 2.,
       1., 2., 2., 1., 1., 2., 2., 2., 2., 1., 1., 2., 2., 1., 1., 1., 2.,
       1., 1., 2., 1., 2., 1., 2., 1., 1., 1., 1., 1., 2., 1., 2., 2., 2.,
       2., 1., 1., 1., 2., 1., 2., 1., 1., 2., 1., 1., 1., 1., 1., 1., 2.,
       2., 1., 2., 1., 1.

In [6]:
# integer encode target
label_encoder = LabelEncoder()
target = label_encoder.fit_transform(target) # integer_encoded
target

array([1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1], dtype=int64)

### Fitur / Atribut untuk X

In [7]:
atribute_labels = ['age', 'sex', 'chest_pain_type', 'resting_blood_pressure', 'serum_cholesterol_mg_per_dl', 'fasting_blood_sugar_gt_120_mg_per_dl', 'resting_ekg_results', 'max_heart_rate_achieved', 'exercise_induced_angina', 'oldpeak_eq_st_depression', 'slope_of_peak_exercise_st_segment', 'num_major_vessels', 'thal']
atribute_value = {}
for i in range(len(atribute_labels)):
    atribute_value[atribute_labels[i]] = data[:,i]
    
features = data[:,0:12]
# features
for j in range(len(atribute_labels)):
    print (atribute_labels[j])
    print (atribute_value[atribute_labels[j]])

age
[70. 67. 57. 64. 74. 65. 56. 59. 60. 63. 59. 53. 44. 61. 57. 71. 46. 53.
 64. 40. 67. 48. 43. 47. 54. 48. 46. 51. 58. 71. 57. 66. 37. 59. 50. 48.
 61. 59. 42. 48. 40. 62. 44. 46. 59. 58. 49. 44. 66. 65. 42. 52. 65. 63.
 45. 41. 61. 60. 59. 62. 57. 51. 44. 60. 63. 57. 51. 58. 44. 47. 61. 57.
 70. 76. 67. 45. 45. 39. 42. 56. 58. 35. 58. 41. 57. 42. 62. 59. 41. 50.
 59. 61. 54. 54. 52. 47. 66. 58. 64. 50. 44. 67. 49. 57. 63. 48. 51. 60.
 59. 45. 55. 41. 60. 54. 42. 49. 46. 56. 66. 56. 49. 54. 57. 65. 54. 54.
 62. 52. 52. 60. 63. 66. 42. 64. 54. 46. 67. 56. 34. 57. 64. 59. 50. 51.
 54. 53. 52. 40. 58. 41. 41. 50. 54. 64. 51. 46. 55. 45. 56. 66. 38. 62.
 55. 58. 43. 64. 50. 53. 45. 65. 69. 69. 67. 68. 34. 62. 51. 46. 67. 50.
 42. 56. 41. 42. 53. 43. 56. 52. 62. 70. 54. 70. 54. 35. 48. 55. 58. 54.
 69. 77. 68. 58. 60. 51. 55. 52. 60. 58. 64. 37. 59. 51. 43. 58. 29. 41.
 63. 51. 54. 44. 54. 65. 57. 63. 35. 41. 62. 43. 58. 52. 61. 39. 45. 52.
 62. 62. 53. 43. 47. 52. 68. 39. 53. 62. 51. 60

In [8]:
# integer encode number of major vessel
atribute_value['thal'] = label_encoder.fit_transform(atribute_value['thal'])
atribute_value['thal']

array([0, 2, 2, 2, 0, 2, 1, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 2, 0, 2, 2, 0,
       0, 0, 0, 0, 0, 0, 2, 0, 2, 1, 0, 2, 2, 2, 2, 0, 0, 0, 2, 0, 0, 2,
       1, 0, 0, 0, 1, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 0, 0, 1, 1,
       0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 2, 2, 0, 1, 0, 0, 2,
       0, 2, 0, 0, 2, 0, 2, 0, 0, 2, 2, 0, 0, 0, 0, 2, 2, 2, 0, 2, 2, 0,
       0, 0, 0, 0, 0, 0, 2, 2, 0, 2, 2, 0, 2, 0, 0, 0, 2, 0, 0, 2, 0, 0,
       0, 0, 2, 0, 0, 0, 0, 2, 1, 0, 2, 0, 2, 2, 0, 2, 2, 0, 0, 0, 0, 0,
       0, 0, 2, 0, 2, 2, 2, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0,
       2, 0, 2, 0, 2, 2, 2, 0, 0, 0, 1, 2, 0, 2, 0, 2, 2, 2, 0, 0, 0, 0,
       0, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 0, 0, 2, 0, 0, 0, 2, 2, 0,
       2, 2, 0, 2, 0, 1, 2, 2, 0, 1, 2, 2, 0, 2, 2, 2, 0, 2, 0, 0, 2, 0,
       0, 0, 0, 2, 1, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0,
       2, 2, 2, 0, 1, 0], dtype=int64)

In [9]:
# Age become category
bins = [0, 2, 18, 35, 65]
# names = ['<2', '2-18', '18-35', '35-65', '65+']
names = [0, 1, 2, 3, 4]

d = dict(enumerate(names, 1))

atribute_value['age'] = np.vectorize(d.get)(np.digitize(atribute_value['age'], bins))
atribute_value['age']

array([4, 4, 3, 3, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 4, 3,
       3, 3, 3, 3, 3, 3, 3, 4, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 4, 4, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 4,
       3, 3, 3, 3, 4, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 2, 3,
       3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 4, 3, 3, 3, 3, 3, 3,
       4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3,
       3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3,
       3, 3, 3, 3, 4, 4, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 4])

In [10]:
# resting_blood_pressure become category
bins = [0, 120, 130, 140, 180]
# names = ['<120', '120-129', '130-139', '140-180', '180>']
# names = ['rb0', 'rb1', 'rb2', 'rb3', 'rb4']
names = [0, 1, 2, 3, 4]


d = dict(enumerate(names, 1))

atribute_value['resting_blood_pressure'] = np.vectorize(d.get)(np.digitize(atribute_value['resting_blood_pressure'], bins))
atribute_value['resting_blood_pressure']

array([2, 0, 1, 1, 1, 1, 2, 0, 3, 3, 2, 3, 3, 2, 1, 0, 3, 3, 0, 3, 1, 2,
       0, 0, 2, 2, 2, 1, 0, 0, 1, 3, 1, 3, 3, 2, 3, 3, 2, 1, 3, 1, 2, 0,
       1, 3, 0, 0, 3, 3, 2, 1, 3, 3, 2, 0, 2, 1, 3, 1, 3, 2, 1, 3, 3, 3,
       3, 2, 0, 0, 1, 1, 3, 3, 0, 3, 0, 0, 1, 1, 3, 1, 3, 2, 0, 3, 1, 3,
       1, 3, 3, 2, 1, 0, 1, 0, 1, 0, 3, 1, 0, 1, 2, 3, 2, 1, 0, 3, 3, 0,
       4, 0, 3, 2, 1, 2, 1, 4, 3, 2, 1, 1, 3, 3, 1, 3, 1, 2, 2, 0, 0, 0,
       3, 1, 3, 3, 3, 1, 0, 2, 3, 2, 3, 1, 4, 1, 0, 0, 2, 0, 0, 1, 0, 2,
       2, 0, 3, 1, 1, 3, 1, 3, 2, 1, 0, 4, 0, 2, 2, 2, 3, 3, 0, 1, 0, 2,
       3, 3, 1, 1, 1, 2, 0, 0, 2, 2, 2, 0, 3, 3, 3, 3, 0, 1, 1, 2, 0, 0,
       3, 1, 0, 1, 1, 3, 3, 3, 0, 0, 1, 2, 3, 1, 1, 1, 2, 2, 2, 0, 1, 1,
       0, 2, 3, 2, 2, 2, 2, 2, 3, 0, 3, 0, 0, 1, 2, 3, 2, 1, 2, 1, 4, 3,
       2, 3, 3, 2, 0, 3, 3, 3, 1, 2, 0, 0, 3, 3, 3, 2, 3, 3, 1, 2, 1, 2,
       0, 3, 1, 3, 3, 3])

In [11]:
# serum_cholesterol_mg_per_dl become category
bins = [0, 200, 240]
# names = ['<200', '200-239', '240>']
# names = ['sc0', 'sc1', 'sc2']
names = [0, 1, 2]

d = dict(enumerate(names, 1))

atribute_value['serum_cholesterol_mg_per_dl'] = np.vectorize(d.get)(np.digitize(atribute_value['serum_cholesterol_mg_per_dl'], bins))
atribute_value['serum_cholesterol_mg_per_dl']

array([2, 2, 2, 2, 2, 0, 2, 1, 2, 2, 1, 1, 1, 1, 2, 0, 2, 1, 1, 0, 1, 2,
       2, 1, 2, 2, 2, 2, 1, 2, 1, 1, 1, 2, 1, 2, 1, 2, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 2, 1, 2, 1, 2, 0, 1, 0, 0, 0, 2, 2, 0, 2, 1, 2, 1, 2,
       2, 2, 2, 2, 2, 2, 2, 0, 1, 2, 1, 0, 1, 1, 1, 0, 2, 1, 1, 2, 1, 2,
       2, 2, 1, 2, 2, 1, 1, 2, 2, 1, 2, 2, 0, 1, 2, 2, 2, 2, 1, 2, 0, 0,
       2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 0, 2, 2, 2, 2, 1, 2, 0, 1, 1, 2, 1,
       1, 2, 1, 0, 2, 2, 1, 1, 1, 2, 1, 1, 2, 2, 1, 0, 1, 2, 2, 1, 2, 2,
       2, 1, 1, 2, 0, 1, 1, 2, 2, 2, 1, 2, 2, 0, 1, 2, 1, 2, 2, 1, 0, 2,
       2, 1, 2, 0, 2, 2, 0, 2, 2, 2, 0, 1, 2, 2, 1, 0, 2, 2, 2, 2, 2, 1,
       1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 1, 2, 1,
       1, 2, 0, 2, 0, 1, 2, 2, 2, 0, 2, 1, 2, 2, 1, 0, 1, 0, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 0, 2, 0, 1, 2, 0, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2,
       1, 0, 2, 2, 0, 2])

In [12]:
# max_heart_rate_achieved become category
bins = [0, 41, 106, 171, 236, 301]
# names = ['<=40', '41-105', '106-170', '171-235', '236-300', '300>=']
# names = ['mh0', 'mh1', 'mh2', 'mh3', 'mh4', 'mh5']
names = [0, 1, 2, 3, 4, 5]

d = dict(enumerate(names, 1))

atribute_value['max_heart_rate_achieved'] = np.vectorize(d.get)(np.digitize(atribute_value['max_heart_rate_achieved'], bins))
atribute_value['max_heart_rate_achieved']

array([2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 3, 2, 3,
       3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 2, 3, 2,
       2, 2, 2, 3, 2, 2, 2, 3, 2, 3, 3, 2, 2, 1, 2, 1, 3, 2, 2, 3, 2, 2,
       3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 1, 2, 2, 2, 2, 3, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2,
       3, 1, 2, 2, 3, 2, 3, 2, 2, 3, 2, 2, 3, 1, 2, 2, 3, 3, 3, 2, 2, 2,
       2, 3, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 3, 2,
       2, 2, 2, 2, 3, 2, 2, 2, 3, 2, 1, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2,
       2, 2, 2, 3, 2, 3, 2, 3, 2, 2, 2, 3, 2, 2, 2, 2, 3, 3, 3, 2, 2, 2,
       2, 2, 3, 2, 3, 2, 1, 2, 2, 3, 2, 2, 3, 2, 2, 2, 2, 2, 2, 3, 2, 3,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 3, 3, 2, 2, 3,
       2, 2, 3, 2, 2, 2])

In [13]:
# oldpeak_eq_st_depression become category
bins = [0, 1, 2, 3, 4, 5, 6]
# names = ['<1', '1-1.9', '2-2.9', '3-3.9', '4-4.9', '5-5.9', '6>']
# names = ['op0', 'op1', 'op2', 'op3', 'op4', 'op5', 'op6']
names = [0, 1, 2, 3, 4, 5, 6]

d = dict(enumerate(names, 1))

atribute_value['oldpeak_eq_st_depression'] = np.vectorize(d.get)(np.digitize(atribute_value['oldpeak_eq_st_depression'], bins))
atribute_value['oldpeak_eq_st_depression']

array([2, 1, 0, 0, 0, 0, 0, 1, 1, 4, 0, 0, 0, 2, 0, 1, 1, 3, 1, 1, 2, 0,
       1, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 3, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       2, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 3, 0, 0, 1, 0, 1, 0, 0, 2, 0,
       0, 0, 0, 0, 3, 0, 0, 1, 0, 0, 3, 0, 0, 0, 2, 1, 0, 2, 1, 0, 0, 4,
       0, 2, 0, 0, 2, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 2, 0, 0,
       3, 0, 0, 0, 0, 0, 0, 4, 2, 1, 2, 3, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 2, 1, 1, 0, 1, 0, 0, 2, 0, 0, 1, 0, 2, 0, 2, 3, 0, 0, 1, 0, 2,
       0, 0, 5, 0, 1, 1, 3, 1, 0, 3, 0, 0, 0, 1, 0, 1, 0, 2, 0, 1, 0, 1,
       4, 3, 0, 0, 0, 1, 0, 0, 0, 1, 2, 0, 1, 2, 1, 2, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 2, 1, 0, 1, 0, 0, 1, 3, 0, 2, 0, 2, 0, 1, 0, 0, 0, 0,
       2, 2, 1, 1, 1, 0, 1, 3, 1, 0, 1, 1, 0, 0, 1, 6, 0, 2, 0, 0, 1, 0,
       0, 3, 1, 1, 0, 0, 3, 2, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 2, 1, 0,
       1, 0, 0, 1, 0, 1])

In [14]:
for j in range(len(atribute_labels)):
    print (atribute_labels[j])
    print (atribute_value[atribute_labels[j]])

age
[4 4 3 3 4 4 3 3 3 3 3 3 3 3 3 4 3 3 3 3 4 3 3 3 3 3 3 3 3 4 3 4 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 4 4 3 3 4 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 4 4
 4 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 4 3 3 3 3 4 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 4 3 3 3 3 4 3 3 3 3 3 3 3 4 3 3 3 3 4 3 2 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 4 3 3 3 3 3 3 3 3 3 4 4 4 4 4 2 3 3 3 4 3 3 3 3 3 3
 3 3 3 3 4 3 4 3 3 3 3 3 3 4 4 4 3 3 3 3 3 3 3 3 3 3 3 3 3 2 3 3 3 3 3 3 4
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 4 3 3 3 3 3 4 4 3 3 3 3 3 3 3 4 3 3 3
 3 3 3 3 3 3 3 3 3 3 4]
sex
[1. 0. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1.
 0. 0. 0. 0. 1. 0. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1.
 1. 0. 1. 1. 0. 0. 0. 0. 1. 0. 0. 1. 1. 0. 1. 0. 1. 1. 1. 0. 0. 1. 1. 0.
 1. 0. 0. 1. 1. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 0. 1. 1. 1. 1.
 1. 1. 0. 0. 0. 1. 0. 1. 1. 1. 1. 0. 1. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 1.
 1. 1. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 1. 1. 1. 0. 0. 1. 0. 1. 1. 1. 1. 1.
 1. 1

In [15]:
# encode one hot coding all of atributes
for j in range(len(atribute_labels)):
    print (atribute_labels[j])
    encoded = to_categorical(atribute_value[atribute_labels[j]])
    print(encoded[:2])
    atribute_value[atribute_labels[j]] = encoded

age
[[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]]
sex
[[0. 1.]
 [1. 0.]]
chest_pain_type
[[0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]]
resting_blood_pressure
[[0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]]
serum_cholesterol_mg_per_dl
[[0. 0. 1.]
 [0. 0. 1.]]
fasting_blood_sugar_gt_120_mg_per_dl
[[1. 0.]
 [1. 0.]]
resting_ekg_results
[[0. 0. 1.]
 [0. 0. 1.]]
max_heart_rate_achieved
[[0. 0. 1. 0.]
 [0. 0. 1. 0.]]
exercise_induced_angina
[[1. 0.]
 [1. 0.]]
oldpeak_eq_st_depression
[[0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]]
slope_of_peak_exercise_st_segment
[[0. 0. 1. 0.]
 [0. 0. 1. 0.]]
num_major_vessels
[[0. 0. 0. 1.]
 [1. 0. 0. 0.]]
thal
[[1. 0. 0.]
 [0. 0. 1.]]


### Show continuous data

In [16]:
atribute_value['resting_blood_pressure'][0]

array([0., 0., 1., 0., 0.], dtype=float32)

In [17]:
atribute_value['serum_cholesterol_mg_per_dl'][0]

array([0., 0., 1.], dtype=float32)

In [18]:
atribute_value['max_heart_rate_achieved'][0]

array([0., 0., 1., 0.], dtype=float32)

In [19]:
atribute_value['oldpeak_eq_st_depression'][0]

array([0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [30]:
vocab = 0
for j in range(len(atribute_labels)):
    print (atribute_labels[j])
    print (len(atribute_value[atribute_labels[j]][0]))
    vocab = vocab+(len(atribute_value[atribute_labels[j]][0]))

vocab

age
5
sex
2
chest_pain_type
5
resting_blood_pressure
5
serum_cholesterol_mg_per_dl
3
fasting_blood_sugar_gt_120_mg_per_dl
2
resting_ekg_results
3
max_heart_rate_achieved
4
exercise_induced_angina
2
oldpeak_eq_st_depression
7
slope_of_peak_exercise_st_segment
4
num_major_vessels
4
thal
3


49

In [57]:
# Generate data [[x1,x2,xn], (y)]
x_y = []
for u in range(len(target)):
#     print ('uuu', u)
    x_temp = []
    for j in range(len(atribute_labels)):
#         print (atribute_labels[j])
#         print ((atribute_value[atribute_labels[j]][u]))
        x_temp.extend(atribute_value[atribute_labels[j]][u])     
        
#     print ('x_temp', ((x_temp)))
    x_y_temp = [x_temp,target[u]]
    x_y.append(x_y_temp)
print ((x_y[:5]))

[[[0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0], 1], [[0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0], 0], [[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0], 1], [[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1