In [824]:
import tensorflow as tf
import numpy as np
from numpy import random
import matplotlib.pyplot as plt
from IPython import display
import pandas as pd 

In [825]:
from numpy import array
from numpy import argmax
from keras.utils import to_categorical

In [826]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm
from sklearn import metrics

In [827]:
#load data
data = np.loadtxt('heart.dat')
print (data)

[[70.  1.  4. ...  3.  3.  2.]
 [67.  0.  3. ...  0.  7.  1.]
 [57.  1.  2. ...  0.  7.  2.]
 ...
 [56.  0.  2. ...  0.  3.  1.]
 [57.  1.  4. ...  0.  6.  1.]
 [67.  1.  4. ...  3.  3.  2.]]


In [828]:
#features
features = data[:,0:12]
print (features)

[[70.   1.   4.  ...  2.4  2.   3. ]
 [67.   0.   3.  ...  1.6  2.   0. ]
 [57.   1.   2.  ...  0.3  1.   0. ]
 ...
 [56.   0.   2.  ...  1.3  2.   0. ]
 [57.   1.   4.  ...  0.4  2.   0. ]
 [67.   1.   4.  ...  1.5  2.   3. ]]


In [829]:
features_labels = ['age', 'sex', 'chest_pain_type', 'resting_blood_pressure', 'serum_cholesterol_mg_per_dl', 'fasting_blood_sugar_gt_120_mg_per_dl', 'resting_ekg_results', 'max_heart_rate_achieved', 'exercise_induced_angina', 'oldpeak_eq_st_depression', 'slope_of_peak_exercise_st_segment', 'num_major_vessels', 'thal']
features_value = {}
for i in range(len(features_labels)):
    features_value[features_labels[i]] = data[:,i]

for j in range(len(features_labels)):
    print (features_labels[j])
    print (features_value[features_labels[j]])

age
[70. 67. 57. 64. 74. 65. 56. 59. 60. 63. 59. 53. 44. 61. 57. 71. 46. 53.
 64. 40. 67. 48. 43. 47. 54. 48. 46. 51. 58. 71. 57. 66. 37. 59. 50. 48.
 61. 59. 42. 48. 40. 62. 44. 46. 59. 58. 49. 44. 66. 65. 42. 52. 65. 63.
 45. 41. 61. 60. 59. 62. 57. 51. 44. 60. 63. 57. 51. 58. 44. 47. 61. 57.
 70. 76. 67. 45. 45. 39. 42. 56. 58. 35. 58. 41. 57. 42. 62. 59. 41. 50.
 59. 61. 54. 54. 52. 47. 66. 58. 64. 50. 44. 67. 49. 57. 63. 48. 51. 60.
 59. 45. 55. 41. 60. 54. 42. 49. 46. 56. 66. 56. 49. 54. 57. 65. 54. 54.
 62. 52. 52. 60. 63. 66. 42. 64. 54. 46. 67. 56. 34. 57. 64. 59. 50. 51.
 54. 53. 52. 40. 58. 41. 41. 50. 54. 64. 51. 46. 55. 45. 56. 66. 38. 62.
 55. 58. 43. 64. 50. 53. 45. 65. 69. 69. 67. 68. 34. 62. 51. 46. 67. 50.
 42. 56. 41. 42. 53. 43. 56. 52. 62. 70. 54. 70. 54. 35. 48. 55. 58. 54.
 69. 77. 68. 58. 60. 51. 55. 52. 60. 58. 64. 37. 59. 51. 43. 58. 29. 41.
 63. 51. 54. 44. 54. 65. 57. 63. 35. 41. 62. 43. 58. 52. 61. 39. 45. 52.
 62. 62. 53. 43. 47. 52. 68. 39. 53. 62. 51. 60

In [830]:
# Age become category
bins = [0, 2, 18, 35, 65]
# names = ['<2', '2-18', '18-35', '35-65', '65+']
names = [0.0, 1.0, 2.0, 3.0, 4.0]

d = dict(enumerate(names, 1))

features_value['age'] = np.vectorize(d.get)(np.digitize(features_value['age'], bins))
print (features_value['age'])

[4. 4. 3. 3. 4. 4. 3. 3. 3. 3. 3. 3. 3. 3. 3. 4. 3. 3. 3. 3. 4. 3. 3. 3.
 3. 3. 3. 3. 3. 4. 3. 4. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 4. 4. 3. 3. 4. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 4. 4. 4. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 4. 3. 3. 3. 3. 4. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 4. 3.
 3. 3. 3. 4. 3. 3. 3. 3. 3. 3. 3. 4. 3. 3. 3. 3. 4. 3. 2. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 4. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 4. 4. 4. 4. 4. 2. 3. 3. 3. 4. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 4. 3. 4.
 3. 3. 3. 3. 3. 3. 4. 4. 4. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 2. 3.
 3. 3. 3. 3. 3. 4. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 4. 3. 3. 3. 3. 3. 4. 4. 3. 3. 3. 3. 3. 3. 3. 4. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 4.]


In [831]:
# resting_blood_pressure become category
bins = [0, 120, 130, 140, 180]
# names = ['<120', '120-129', '130-139', '140-180', '180>']
# names = ['rb0', 'rb1', 'rb2', 'rb3', 'rb4']
names = [0.0, 1.0, 2.0, 3.0, 4.0]


d = dict(enumerate(names, 1))

features_value['resting_blood_pressure'] = np.vectorize(d.get)(np.digitize(features_value['resting_blood_pressure'], bins))
print (features_value['resting_blood_pressure'])

[2. 0. 1. 1. 1. 1. 2. 0. 3. 3. 2. 3. 3. 2. 1. 0. 3. 3. 0. 3. 1. 2. 0. 0.
 2. 2. 2. 1. 0. 0. 1. 3. 1. 3. 3. 2. 3. 3. 2. 1. 3. 1. 2. 0. 1. 3. 0. 0.
 3. 3. 2. 1. 3. 3. 2. 0. 2. 1. 3. 1. 3. 2. 1. 3. 3. 3. 3. 2. 0. 0. 1. 1.
 3. 3. 0. 3. 0. 0. 1. 1. 3. 1. 3. 2. 0. 3. 1. 3. 1. 3. 3. 2. 1. 0. 1. 0.
 1. 0. 3. 1. 0. 1. 2. 3. 2. 1. 0. 3. 3. 0. 4. 0. 3. 2. 1. 2. 1. 4. 3. 2.
 1. 1. 3. 3. 1. 3. 1. 2. 2. 0. 0. 0. 3. 1. 3. 3. 3. 1. 0. 2. 3. 2. 3. 1.
 4. 1. 0. 0. 2. 0. 0. 1. 0. 2. 2. 0. 3. 1. 1. 3. 1. 3. 2. 1. 0. 4. 0. 2.
 2. 2. 3. 3. 0. 1. 0. 2. 3. 3. 1. 1. 1. 2. 0. 0. 2. 2. 2. 0. 3. 3. 3. 3.
 0. 1. 1. 2. 0. 0. 3. 1. 0. 1. 1. 3. 3. 3. 0. 0. 1. 2. 3. 1. 1. 1. 2. 2.
 2. 0. 1. 1. 0. 2. 3. 2. 2. 2. 2. 2. 3. 0. 3. 0. 0. 1. 2. 3. 2. 1. 2. 1.
 4. 3. 2. 3. 3. 2. 0. 3. 3. 3. 1. 2. 0. 0. 3. 3. 3. 2. 3. 3. 1. 2. 1. 2.
 0. 3. 1. 3. 3. 3.]


In [832]:
# serum_cholesterol_mg_per_dl become category
bins = [0, 200, 240]
# names = ['<200', '200-239', '240>']
# names = ['sc0', 'sc1', 'sc2']
names = [0.0, 1.0, 2.0]

d = dict(enumerate(names, 1))

features_value['serum_cholesterol_mg_per_dl'] = np.vectorize(d.get)(np.digitize(features_value['serum_cholesterol_mg_per_dl'], bins))
print (features_value['serum_cholesterol_mg_per_dl'])

[2. 2. 2. 2. 2. 0. 2. 1. 2. 2. 1. 1. 1. 1. 2. 0. 2. 1. 1. 0. 1. 2. 2. 1.
 2. 2. 2. 2. 1. 2. 1. 1. 1. 2. 1. 2. 1. 2. 0. 1. 1. 1. 1. 0. 1. 1. 0. 0.
 2. 1. 2. 1. 2. 0. 1. 0. 0. 0. 2. 2. 0. 2. 1. 2. 1. 2. 2. 2. 2. 2. 2. 2.
 2. 0. 1. 2. 1. 0. 1. 1. 1. 0. 2. 1. 1. 2. 1. 2. 2. 2. 1. 2. 2. 1. 1. 2.
 2. 1. 2. 2. 0. 1. 2. 2. 2. 2. 1. 2. 0. 0. 2. 1. 2. 2. 2. 2. 2. 2. 1. 2.
 0. 2. 2. 2. 2. 1. 2. 0. 1. 1. 2. 1. 1. 2. 1. 0. 2. 2. 1. 1. 1. 2. 1. 1.
 2. 2. 1. 0. 1. 2. 2. 1. 2. 2. 2. 1. 1. 2. 0. 1. 1. 2. 2. 2. 1. 2. 2. 0.
 1. 2. 1. 2. 2. 1. 0. 2. 2. 1. 2. 0. 2. 2. 0. 2. 2. 2. 0. 1. 2. 2. 1. 0.
 2. 2. 2. 2. 2. 1. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 1. 1. 1. 1.
 2. 1. 2. 1. 1. 2. 0. 2. 0. 1. 2. 2. 2. 0. 2. 1. 2. 2. 1. 0. 1. 0. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 0. 2. 0. 1. 2. 0. 1. 2. 2. 2. 2. 2. 2. 1. 2. 2.
 1. 0. 2. 2. 0. 2.]


In [833]:
# max_heart_rate_achieved become category
bins = [0, 41, 106, 171, 236, 301]
# names = ['<=40', '41-105', '106-170', '171-235', '236-300', '300>=']
# names = ['mh0', 'mh1', 'mh2', 'mh3', 'mh4', 'mh5']
names = [0.0, 1.0, 2.0, 3.0, 4.0, 5.0]

d = dict(enumerate(names, 1))

features_value['max_heart_rate_achieved'] = np.vectorize(d.get)(np.digitize(features_value['max_heart_rate_achieved'], bins))
print (features_value['max_heart_rate_achieved'])

[2. 2. 2. 1. 2. 2. 2. 2. 2. 2. 2. 2. 3. 2. 2. 2. 2. 2. 2. 3. 2. 3. 3. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 3. 3. 2. 3. 2. 2. 2. 2. 3.
 2. 2. 2. 3. 2. 3. 3. 2. 2. 1. 2. 1. 3. 2. 2. 3. 2. 2. 3. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 3. 3. 3. 1. 2. 2. 2. 2. 3. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 3. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 1.
 2. 2. 1. 2. 2. 2. 1. 2. 2. 2. 2. 2. 3. 1. 2. 2. 3. 2. 3. 2. 2. 3. 2. 2.
 3. 1. 2. 2. 3. 3. 3. 2. 2. 2. 2. 3. 2. 2. 2. 2. 3. 2. 2. 2. 2. 2. 2. 2.
 2. 3. 2. 2. 2. 2. 3. 2. 2. 2. 2. 2. 3. 2. 2. 2. 3. 2. 1. 2. 2. 2. 2. 2.
 2. 2. 3. 2. 2. 2. 2. 2. 2. 3. 2. 3. 2. 3. 2. 2. 2. 3. 2. 2. 2. 2. 3. 3.
 3. 2. 2. 2. 2. 2. 3. 2. 3. 2. 1. 2. 2. 3. 2. 2. 3. 2. 2. 2. 2. 2. 2. 3.
 2. 3. 2. 2. 2. 2. 2. 2. 2. 2. 2. 3. 2. 2. 2. 2. 2. 2. 2. 3. 3. 2. 2. 3.
 2. 2. 3. 2. 2. 2.]


In [834]:
# oldpeak_eq_st_depression become category
bins = [0, 1, 2, 3, 4, 5, 6]
# names = ['<1', '1-1.9', '2-2.9', '3-3.9', '4-4.9', '5-5.9', '6>']
# names = ['op0', 'op1', 'op2', 'op3', 'op4', 'op5', 'op6']
names = [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0]

d = dict(enumerate(names, 1))

features_value['oldpeak_eq_st_depression'] = np.vectorize(d.get)(np.digitize(features_value['oldpeak_eq_st_depression'], bins))
print (features_value['oldpeak_eq_st_depression'])

[2. 1. 0. 0. 0. 0. 0. 1. 1. 4. 0. 0. 0. 2. 0. 1. 1. 3. 1. 1. 2. 0. 1. 0.
 0. 0. 0. 0. 2. 0. 0. 2. 0. 3. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 2. 0. 0. 0.
 0. 1. 1. 0. 0. 0. 0. 0. 3. 0. 0. 1. 0. 1. 0. 0. 2. 0. 0. 0. 0. 0. 3. 0.
 0. 1. 0. 0. 3. 0. 0. 0. 2. 1. 0. 2. 1. 0. 0. 4. 0. 2. 0. 0. 2. 0. 1. 1.
 0. 0. 0. 1. 0. 1. 0. 1. 1. 0. 1. 2. 0. 0. 3. 0. 0. 0. 0. 0. 0. 4. 2. 1.
 2. 3. 1. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 2. 1. 1. 0. 1. 0. 0. 2. 0. 0. 1.
 0. 2. 0. 2. 3. 0. 0. 1. 0. 2. 0. 0. 5. 0. 1. 1. 3. 1. 0. 3. 0. 0. 0. 1.
 0. 1. 0. 2. 0. 1. 0. 1. 4. 3. 0. 0. 0. 1. 0. 0. 0. 1. 2. 0. 1. 2. 1. 2.
 0. 0. 0. 1. 1. 1. 1. 0. 1. 0. 2. 1. 0. 1. 0. 0. 1. 3. 0. 2. 0. 2. 0. 1.
 0. 0. 0. 0. 2. 2. 1. 1. 1. 0. 1. 3. 1. 0. 1. 1. 0. 0. 1. 6. 0. 2. 0. 0.
 1. 0. 0. 3. 1. 1. 0. 0. 3. 2. 1. 0. 0. 0. 1. 0. 1. 1. 0. 1. 0. 2. 1. 0.
 1. 0. 0. 1. 0. 1.]


In [835]:
#target
target = data [:,13]
print (target)

[2. 1. 2. 1. 1. 1. 2. 2. 2. 2. 1. 1. 1. 2. 1. 1. 2. 2. 1. 1. 2. 1. 1. 1.
 1. 1. 1. 1. 2. 1. 2. 1. 1. 2. 2. 2. 2. 2. 1. 1. 2. 1. 1. 1. 2. 1. 2. 2.
 2. 2. 2. 1. 1. 1. 1. 1. 2. 1. 2. 2. 1. 2. 1. 1. 1. 2. 1. 2. 1. 2. 2. 1.
 1. 1. 1. 2. 1. 1. 1. 1. 2. 2. 2. 1. 1. 1. 1. 1. 1. 2. 1. 2. 2. 2. 2. 2.
 1. 2. 1. 1. 1. 2. 1. 2. 2. 2. 1. 2. 2. 1. 2. 1. 2. 1. 1. 1. 2. 2. 1. 2.
 2. 2. 2. 1. 1. 1. 2. 1. 1. 2. 2. 2. 1. 2. 1. 1. 1. 2. 1. 1. 2. 1. 2. 1.
 2. 2. 2. 2. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 2. 2. 2. 1. 2. 1. 1. 1. 1.
 1. 2. 1. 2. 2. 1. 1. 2. 2. 2. 2. 1. 1. 2. 2. 1. 1. 1. 2. 1. 1. 2. 1. 2.
 1. 2. 1. 1. 1. 1. 1. 2. 1. 2. 2. 2. 2. 1. 1. 1. 2. 1. 2. 1. 1. 2. 1. 1.
 1. 1. 1. 1. 2. 2. 1. 2. 1. 1. 2. 2. 1. 1. 2. 2. 1. 2. 1. 2. 1. 2. 1. 1.
 2. 1. 1. 2. 1. 2. 2. 1. 2. 2. 2. 1. 2. 1. 1. 1. 1. 2. 2. 1. 1. 2. 2. 1.
 2. 1. 1. 1. 1. 2.]


In [836]:
# Generate data [[x1,x2,xn], (y)]
data_temp = []
for i in range(len(target)):
    x_temp = []
    for j in range(len(features_labels)):
        x_temp.append(features_value[features_labels[j]][i])   
        
    xy_temp = [x_temp,target[i]]
    data_temp.append(xy_temp)
    
print (data_temp[:3])

[[[4.0, 1.0, 4.0, 2.0, 2.0, 0.0, 2.0, 2.0, 0.0, 2.0, 2.0, 3.0, 3.0], 2.0], [[4.0, 0.0, 3.0, 0.0, 2.0, 0.0, 2.0, 2.0, 0.0, 1.0, 2.0, 0.0, 7.0], 1.0], [[3.0, 1.0, 2.0, 1.0, 2.0, 0.0, 0.0, 2.0, 0.0, 0.0, 1.0, 0.0, 7.0], 2.0]]


In [837]:
#split data train and data test
train, test = train_test_split(data_temp, test_size = 0.2)
print(len(train))
print(len(test))

216
54


In [838]:
x_train = [train[i][0] for i in range(len(train))]
y_train = [train[i][1] for i in range(len(train))]
print (x_train)

[[3.0, 1.0, 3.0, 1.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 1.0, 0.0, 3.0], [3.0, 0.0, 3.0, 1.0, 2.0, 0.0, 0.0, 3.0, 0.0, 0.0, 1.0, 0.0, 3.0], [4.0, 0.0, 3.0, 1.0, 1.0, 0.0, 2.0, 2.0, 0.0, 1.0, 2.0, 0.0, 3.0], [3.0, 0.0, 2.0, 2.0, 2.0, 0.0, 0.0, 2.0, 0.0, 0.0, 2.0, 0.0, 3.0], [3.0, 1.0, 3.0, 1.0, 2.0, 0.0, 0.0, 2.0, 1.0, 1.0, 2.0, 0.0, 7.0], [3.0, 0.0, 4.0, 2.0, 2.0, 0.0, 0.0, 2.0, 1.0, 1.0, 2.0, 0.0, 7.0], [3.0, 0.0, 4.0, 0.0, 2.0, 0.0, 2.0, 2.0, 0.0, 0.0, 2.0, 0.0, 3.0], [4.0, 1.0, 4.0, 0.0, 2.0, 0.0, 2.0, 2.0, 0.0, 0.0, 1.0, 2.0, 6.0], [3.0, 1.0, 2.0, 1.0, 1.0, 0.0, 0.0, 2.0, 0.0, 0.0, 1.0, 0.0, 3.0], [3.0, 1.0, 4.0, 1.0, 2.0, 0.0, 0.0, 1.0, 1.0, 1.0, 2.0, 2.0, 7.0], [3.0, 1.0, 2.0, 0.0, 1.0, 0.0, 0.0, 2.0, 0.0, 0.0, 1.0, 0.0, 3.0], [3.0, 1.0, 3.0, 2.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 1.0, 0.0, 3.0], [3.0, 1.0, 4.0, 0.0, 1.0, 0.0, 0.0, 2.0, 0.0, 0.0, 1.0, 0.0, 7.0], [3.0, 0.0, 3.0, 0.0, 2.0, 0.0, 2.0, 2.0, 0.0, 0.0, 1.0, 0.0, 3.0], [3.0, 1.0, 4.0, 3.0, 1.0, 1.0, 2.0, 2.0, 1.0, 3.0, 3.0, 0.0, 

In [839]:
print (y_train)

[1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 1.0, 2.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 2.0, 2.0, 1.0, 2.0, 1.0, 1.0, 1.0, 2.0, 1.0, 1.0, 2.0, 1.0, 2.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 2.0, 1.0, 1.0, 1.0, 2.0, 1.0, 1.0, 2.0, 2.0, 2.0, 2.0, 1.0, 2.0, 2.0, 1.0, 1.0, 2.0, 2.0, 2.0, 1.0, 1.0, 2.0, 1.0, 1.0, 2.0, 1.0, 2.0, 1.0, 1.0, 2.0, 2.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 1.0, 2.0, 2.0, 2.0, 2.0, 1.0, 2.0, 1.0, 2.0, 2.0, 2.0, 1.0, 2.0, 1.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 1.0, 1.0, 2.0, 2.0, 2.0, 1.0, 2.0, 1.0, 1.0, 2.0, 2.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 1.0, 2.0, 2.0, 2.0, 2.0, 1.0, 1.0, 2.0, 2.0, 2.0, 1.0, 2.0, 1.0, 2.0, 2.0, 2.0, 2.0, 1.0, 1.0, 1.0, 2.0, 1.0, 2.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 2.0, 1.0, 2.0, 1.0, 2.0, 1.0, 2.0, 2.0, 1.0, 2.0, 1.0, 2.0, 2.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 2.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 2.0, 1.0, 1.0, 1.0, 1.0,

In [840]:
x_test = [test[i][0] for i in range(len(test))]
y_test = [test[i][1] for i in range(len(test))]
print (x_test)

[[3.0, 0.0, 2.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 2.0, 0.0, 3.0], [3.0, 1.0, 1.0, 3.0, 0.0, 0.0, 0.0, 3.0, 1.0, 1.0, 1.0, 0.0, 7.0], [3.0, 1.0, 4.0, 3.0, 2.0, 0.0, 0.0, 1.0, 1.0, 1.0, 2.0, 1.0, 7.0], [3.0, 1.0, 2.0, 3.0, 1.0, 0.0, 0.0, 2.0, 1.0, 0.0, 1.0, 0.0, 3.0], [3.0, 1.0, 3.0, 0.0, 1.0, 0.0, 0.0, 2.0, 1.0, 0.0, 1.0, 1.0, 7.0], [3.0, 1.0, 4.0, 0.0, 0.0, 0.0, 2.0, 2.0, 0.0, 0.0, 1.0, 0.0, 7.0], [4.0, 1.0, 4.0, 1.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 1.0, 0.0, 7.0], [3.0, 1.0, 3.0, 2.0, 2.0, 1.0, 2.0, 2.0, 1.0, 0.0, 2.0, 1.0, 6.0], [3.0, 1.0, 3.0, 3.0, 0.0, 1.0, 0.0, 3.0, 0.0, 0.0, 1.0, 1.0, 7.0], [3.0, 1.0, 3.0, 1.0, 1.0, 1.0, 0.0, 2.0, 0.0, 2.0, 2.0, 1.0, 6.0], [3.0, 1.0, 3.0, 3.0, 0.0, 1.0, 0.0, 2.0, 0.0, 0.0, 1.0, 0.0, 7.0], [3.0, 1.0, 3.0, 2.0, 2.0, 0.0, 0.0, 2.0, 0.0, 1.0, 1.0, 1.0, 3.0], [3.0, 1.0, 2.0, 2.0, 1.0, 0.0, 0.0, 2.0, 0.0, 0.0, 2.0, 0.0, 6.0], [3.0, 1.0, 4.0, 0.0, 1.0, 0.0, 2.0, 2.0, 1.0, 3.0, 2.0, 0.0, 3.0], [3.0, 1.0, 4.0, 1.0, 2.0, 0.0, 2.0, 2.0, 1.0, 3.0, 2.0, 2.0, 

In [841]:
print (y_test)

[1.0, 1.0, 2.0, 1.0, 1.0, 2.0, 1.0, 2.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 2.0, 1.0, 2.0, 1.0, 1.0, 2.0, 2.0, 1.0, 1.0, 2.0, 2.0, 2.0, 1.0, 2.0, 2.0, 1.0, 2.0, 2.0, 2.0, 2.0, 1.0, 2.0, 2.0, 2.0, 1.0, 1.0, 1.0, 2.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 2.0, 2.0]


In [842]:
# Complete Code
from keras.datasets import imdb
from keras.models import Sequential
from keras.layers import Dense, GRU, Flatten, LSTM, Dropout
from keras.layers.embeddings import Embedding
from keras.preprocessing import sequence

In [843]:
# define the model
# dimension = 13
# vocab_size = 0
# input_length = menyamakan semua inputan sequence
model = Sequential()
#model.add(LSTM(4, input_shape=(1, look_back)))
#model.add(Dense(1))
#model.compile(loss='mean_squared_error', optimizer='adam')
model.add(Dense(50, input_dim=2, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

#model.add(Embedding(15, 32, input_length = 10))
#model.add(Flatten())
#model.add(Dense(1, activation='sigmoid'))
# compile the model
#model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
# summarize the model
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_30 (Dense)             (None, 50)                150       
_________________________________________________________________
dense_31 (Dense)             (None, 3)                 153       
Total params: 303
Trainable params: 303
Non-trainable params: 0
_________________________________________________________________
None


In [844]:
model.fit(x_train, y_train, epochs = 100, batch_size = 32, validation_data=(x_test, y_test), verbose = 0)
#, validation_data=(x_test, y_test), verbose = 1)
# Final evaluation of the model
#scores = model.evaluate(x_test, y_test)
#print('Score: {}'.format(score))
#print("Accuracy: %.2f%%" % (scores[1]*100))

# Predict the label for test data
#y_predict = model.predict(x_test)

ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 1 array(s), but instead got the following list of 216 arrays: [array([[3.],
       [1.],
       [3.],
       [1.],
       [0.],
       [0.],
       [0.],
       [2.],
       [0.],
       [0.],
       [1.],
       [0.],
       [3.]]), array([[3.],
       [0.],
  ...

In [ ]:
# a simple random forest model
model=RandomForestClassifier(n_estimators=100)# a simple random forest model
model.fit(x_train,y_train)# now fit our model for traiing data

In [ ]:
prediction=model.predict(x_test)
metrics.accuracy_score(prediction,y_test)

In [ ]:
# lets now try with SVM
model = svm.SVC()
model.fit(x_train,y_train)
prediction=model.predict(x_test)
metrics.accuracy_score(prediction,y_test)

In [ ]:
# try with decisiontree
model = DecisionTreeClassifier()
prediction_var = [data_temp[i][0] for i in range(len(data_temp))]
outcome_var = [data_temp[i][1] for i in range(len(data_temp))]
classification_model(model,data,prediction_var,outcome_var)