In [6]:
import pandas as pd
import numpy as np
import csv

In [18]:
data = np.loadtxt( 'heart.dat' )
data

array([[70.,  1.,  4., ...,  3.,  3.,  2.],
       [67.,  0.,  3., ...,  0.,  7.,  1.],
       [57.,  1.,  2., ...,  0.,  7.,  2.],
       ...,
       [56.,  0.,  2., ...,  0.,  3.,  1.],
       [57.,  1.,  4., ...,  0.,  6.,  1.],
       [67.,  1.,  4., ...,  3.,  3.,  2.]])

In [20]:
features = data[:,0:12]
features

array([[70. ,  1. ,  4. , ...,  2.4,  2. ,  3. ],
       [67. ,  0. ,  3. , ...,  1.6,  2. ,  0. ],
       [57. ,  1. ,  2. , ...,  0.3,  1. ,  0. ],
       ...,
       [56. ,  0. ,  2. , ...,  1.3,  2. ,  0. ],
       [57. ,  1. ,  4. , ...,  0.4,  2. ,  0. ],
       [67. ,  1. ,  4. , ...,  1.5,  2. ,  3. ]])

In [21]:
target = data[:,13]
target

array([2., 1., 2., 1., 1., 1., 2., 2., 2., 2., 1., 1., 1., 2., 1., 1., 2.,
       2., 1., 1., 2., 1., 1., 1., 1., 1., 1., 1., 2., 1., 2., 1., 1., 2.,
       2., 2., 2., 2., 1., 1., 2., 1., 1., 1., 2., 1., 2., 2., 2., 2., 2.,
       1., 1., 1., 1., 1., 2., 1., 2., 2., 1., 2., 1., 1., 1., 2., 1., 2.,
       1., 2., 2., 1., 1., 1., 1., 2., 1., 1., 1., 1., 2., 2., 2., 1., 1.,
       1., 1., 1., 1., 2., 1., 2., 2., 2., 2., 2., 1., 2., 1., 1., 1., 2.,
       1., 2., 2., 2., 1., 2., 2., 1., 2., 1., 2., 1., 1., 1., 2., 2., 1.,
       2., 2., 2., 2., 1., 1., 1., 2., 1., 1., 2., 2., 2., 1., 2., 1., 1.,
       1., 2., 1., 1., 2., 1., 2., 1., 2., 2., 2., 2., 2., 1., 1., 1., 1.,
       1., 1., 1., 2., 1., 1., 2., 2., 2., 1., 2., 1., 1., 1., 1., 1., 2.,
       1., 2., 2., 1., 1., 2., 2., 2., 2., 1., 1., 2., 2., 1., 1., 1., 2.,
       1., 1., 2., 1., 2., 1., 2., 1., 1., 1., 1., 1., 2., 1., 2., 2., 2.,
       2., 1., 1., 1., 2., 1., 2., 1., 1., 2., 1., 1., 1., 1., 1., 1., 2.,
       2., 1., 2., 1., 1.