In [3]:
import pandas as pd
import numpy as np

In [4]:
data = np.loadtxt( 'heart.dat' )
data

array([[70.,  1.,  4., ...,  3.,  3.,  2.],
       [67.,  0.,  3., ...,  0.,  7.,  1.],
       [57.,  1.,  2., ...,  0.,  7.,  2.],
       ...,
       [56.,  0.,  2., ...,  0.,  3.,  1.],
       [57.,  1.,  4., ...,  0.,  6.,  1.],
       [67.,  1.,  4., ...,  3.,  3.,  2.]])

In [5]:
X = data[:,0:12]
X

array([[70. ,  1. ,  4. , ...,  2.4,  2. ,  3. ],
       [67. ,  0. ,  3. , ...,  1.6,  2. ,  0. ],
       [57. ,  1. ,  2. , ...,  0.3,  1. ,  0. ],
       ...,
       [56. ,  0. ,  2. , ...,  1.3,  2. ,  0. ],
       [57. ,  1. ,  4. , ...,  0.4,  2. ,  0. ],
       [67. ,  1. ,  4. , ...,  1.5,  2. ,  3. ]])

In [6]:
y = data[:,13]
y

array([2., 1., 2., 1., 1., 1., 2., 2., 2., 2., 1., 1., 1., 2., 1., 1., 2.,
       2., 1., 1., 2., 1., 1., 1., 1., 1., 1., 1., 2., 1., 2., 1., 1., 2.,
       2., 2., 2., 2., 1., 1., 2., 1., 1., 1., 2., 1., 2., 2., 2., 2., 2.,
       1., 1., 1., 1., 1., 2., 1., 2., 2., 1., 2., 1., 1., 1., 2., 1., 2.,
       1., 2., 2., 1., 1., 1., 1., 2., 1., 1., 1., 1., 2., 2., 2., 1., 1.,
       1., 1., 1., 1., 2., 1., 2., 2., 2., 2., 2., 1., 2., 1., 1., 1., 2.,
       1., 2., 2., 2., 1., 2., 2., 1., 2., 1., 2., 1., 1., 1., 2., 2., 1.,
       2., 2., 2., 2., 1., 1., 1., 2., 1., 1., 2., 2., 2., 1., 2., 1., 1.,
       1., 2., 1., 1., 2., 1., 2., 1., 2., 2., 2., 2., 2., 1., 1., 1., 1.,
       1., 1., 1., 2., 1., 1., 2., 2., 2., 1., 2., 1., 1., 1., 1., 1., 2.,
       1., 2., 2., 1., 1., 2., 2., 2., 2., 1., 1., 2., 2., 1., 1., 1., 2.,
       1., 1., 2., 1., 2., 1., 2., 1., 1., 1., 1., 1., 2., 1., 2., 2., 2.,
       2., 1., 1., 1., 2., 1., 2., 1., 1., 2., 1., 1., 1., 1., 1., 1., 2.,
       2., 1., 2., 1., 1.

In [7]:
from sklearn.model_selection import KFold

In [19]:
kf = KFold(n_splits=10)
kf.get_n_splits(X)

10

In [20]:
for train_index, test_index in kf.split(X):
    print("\nTRAIN:", train_index, "\n\nTEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]


TRAIN: [ 27  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44
  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62
  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80
  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98
  99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116
 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134
 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152
 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170
 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188
 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206
 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224
 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242
 243 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260
 261 262 263 264 265 266 267 268 269] 

TES